# -*- coding: utf-8 -*-
"""INSURANCE_APP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S-lHfQWkuZ-Gj3M6C-Gz-qpFaD7HRdlV
"""

import streamlit as st
import numpy as np
import pickle

# Load the trained model
@st.cache_resource
def load_model():
    with open('insurance_model.pkl', 'rb') as f:
        return pickle.load(f)

model = load_model()

# Page configuration
st.set_page_config(page_title="Insurance Estimator", layout="centered")

# Title
st.title("💰 Insurance Charges Estimator")
st.write("Estimate your medical insurance cost using basic personal information.")

# Input Form
st.header("🧾 Enter Your Details")
with st.form("user_input_form"):
    age = st.slider("Age", 18, 100, 30)
    sex = st.radio("Sex", ["Male", "Female"])
    bmi = st.number_input("BMI (Body Mass Index)", min_value=10.0, max_value=50.0, value=25.0)
    children = st.number_input("Number of Children", min_value=0, max_value=10, step=1)
    smoker = st.radio("Smoker", ["Yes", "No"])

    submit = st.form_submit_button("Estimate Charges")

# Predict and Display
if submit:
    # Encode inputs
    sex_code = 1 if sex == "Male" else 0
    smoker_code = 1 if smoker == "Yes" else 0

    # Prepare data and predict
    input_data = np.array([[age, sex_code, bmi, children, smoker_code]])
    prediction = model.predict(input_data)[0]

    # Show result
    st.success(f"💵 Estimated Insurance Charges: **${prediction:,.2f}**")
