# -*- coding: utf-8 -*-
"""MedicalCostapp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uK2BDY9_I4RbmsRtr_vaoAW0ye1RhD07
"""

import streamlit as st
import numpy as np
import pickle
import os

# Load model
@st.cache_resource
def load_model():
    model_path = 'insurance_model.pkl'
    if not os.path.exists(model_path):
        st.error("🚫 Model file not found. Please upload 'insurance_model.pkl' to the same directory.")
        st.stop()
    with open(model_path, 'rb') as f:
        return pickle.load(f)

model = load_model()

# Page setup
st.set_page_config(
    page_title="💼 Insurance Predictor",
    layout="centered",
    page_icon="💰"
)

# Custom styles and title
st.markdown("""
    <style>
        .banner {
            background-color: #D1ECF1;
            color: #0C5460;
            padding: 10px;
            border-radius: 10px;
            text-align: center;
            animation: moveBanner 15s linear infinite;
        }
        @keyframes moveBanner {
            0% {transform: translateX(-100%);}
            50% {transform: translateX(0);}
            100% {transform: translateX(100%);}
        }
        .title {
            font-size: 48px;
            color: #4B8BBE;
            text-align: center;
        }
        .subtitle {
            font-size: 18px;
            color: #666;
            text-align: center;
        }
    </style>
    <div class="title">💰 Insurance Charges Estimator</div>
    <div class="subtitle">Accurate predictions using AI - Powered by Linear Regression</div>
    <br>
    <div class="banner">🏥 Predict Medical Charges Instantly | Developed by konjam_kadhalxx | Streamlit Pro UI 🌟</div>
""", unsafe_allow_html=True)

# Input form
with st.form("prediction_form", clear_on_submit=False):
    st.subheader("🧾 Enter Personal Information")

    col1, col2 = st.columns(2)

    with col1:
        age = st.slider("🎂 Age", 18, 100, 30)
        bmi = st.number_input("⚖️ BMI", min_value=10.0, max_value=50.0, value=25.0)
        children = st.number_input("👶 Number of Children", min_value=0, max_value=10, step=1)

    with col2:
        sex = st.radio("🧑 Sex", ['Male', 'Female'], horizontal=True)
        smoker = st.radio("🚬 Smoker", ['Yes', 'No'], horizontal=True)

    # Encode inputs
    sex = 1 if sex == "Male" else 0
    smoker = 1 if smoker == "Yes" else 0

    submit = st.form_submit_button("🔍 Estimate Charges")

# Prediction and result
if submit:
    data = np.array([[age, sex, bmi, children, smoker]])
    prediction = model.predict(data)[0]

    st.markdown("""
        <style>
        .runner {
            font-size: 36px;
            animation: run 2.5s linear forwards;
        }
        @keyframes run {
            0% { margin-left: 0%; opacity: 0; }
            20% { opacity: 1; }
            100% { margin-left: 90%; opacity: 0; }
        }
        </style>
        <div class='runner'>🏃‍♂️</div>
    """, unsafe_allow_html=True)

    st.success(f"💵 Estimated Charges: **${prediction:,.2f}**")
